sudo: false
language: rust
branches:
  only:
  - master
  - /^solana-.*$/

cache: cargo

matrix:
  fast_finish: false
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
  allow_failures:
  - rust: nightly

script:
  - cargo build --all
  - cargo test --all
  
